name: Build sketch
on: [push, pull_request]
jobs:
  build:
    name: Compile sketch for esp32
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout ESPAsyncWebServer library
        uses: actions/checkout@v2
        with:
          repository: me-no-dev/ESPAsyncWebServer
          ref: master
          path: CustomESPAsyncWebServer # must contain string "Custom"

      - name: Checkout AsyncElegantOTA library
        uses: actions/checkout@v2
        with:
          repository: ayushsharma82/AsyncElegantOTA
          ref: master
          path: CustomAsyncElegantOTA

      - name: Checkout AsyncTCP library
        uses: actions/checkout@v2
        with:
          repository: me-no-dev/AsyncTCP
          ref: master
          path: CustomAsyncTCP

      - name: Checkout ErriezMHZ19B library
        uses: actions/checkout@v2
        with:
          repository: Erriez/ErriezMHZ19B
          ref: master
          path: CustomErriezMHZ19B

      - name: Checkout Adafruit_NeoPixel library
        uses: actions/checkout@v2
        with:
          repository: adafruit/Adafruit_NeoPixel
          ref: master
          path: CustomAdafruit_NeoPixel

      - name: "Compile sketch"
        uses: ArminJo/arduino-test-compile@v3
        with:
          sketch-names: "air_quality.ino"
          arduino-board-fqbn: "esp32:esp32:esp32"
          platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          required-libraries: HomeSpan,SoftwareSerial
          # sketches-exclude: WhistleSwitch 50Hz
          # build-properties: '{ "air_quality": "-DDEBUG -DFREQUENCY_RANGE_LOW", "SimpleFrequencyDetector": "-DINFO" }'
